### ISSUE TITLE
wrong address

### ISSUE THREAD

**Issue by chansigit** [aertslab/LoomXpy#10]
look at this page
https://scope.aertslab.org/#/0fb6416e-d236-4837-9f24-f34ef413d801/*/welcome
---
SCope compatible loom files can be generated using the following packages:
R: SCopeLoomR
Python: LoomXpy or pySCENIC
---

the link to LoomXpy is wrong. please correct it or users can't find you.

**Comment by ghuls** [comment]
Fixed.
